branches:
  - "main"
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - path: "@semantic-release/npm"
    pkgRoot: "react/build"
  - path: "@semantic-release/npm"
    pkgRoot: "server"
  - path: "@codedependant/semantic-release-docker"
    dockerProject: "timada0"
    dockerImage: "websocket"
  - path: "@semantic-release/github"
    assets:
      - "react/dist/**/*.js"
      - "server/dist/**/*.js"
  - path: "@semantic-release/git"
    assets:
      - "react/package.json"
      - "server/package.json"
